### PR TITLE
os/kola: change slack message formatting

### PR DESCRIPTION
**Pull request by arithx**
Changes from a single `,` delimeter to `,<space>`. This requires a change from
using `paste` to `sed`.

### CODE REVIEW

**Comment by bgilbert** [comment]
While you're here, could you have the message link directly to the job log?

**Comment by arithx** [comment]
@bgilbert to `console` or `consoleFull`?

**Comment by bgilbert** [comment]
@arithx No personal preference.  Others may have opinions.

**Comment by arithx** [comment]
Updated to have it link to the `console` instead of the `BUILD_URL`

**Pull request merged**
